-- Insert default admin
INSERT OR IGNORE INTO admins (email, password) VALUES 
  ('admin@rummikub.com', '$2a$10$N9qo8uLOickgx2ZMRZoMye7VFnjZuJhNJPVJJJJJJJJJJJJJJJJJO'); -- password: admin123

-- Insert bot nicknames (800+ names)
INSERT OR IGNORE INTO bot_nicknames (nickname) VALUES 
  ('אברהם'), ('יצחק'), ('יעקב'), ('משה'), ('אהרן'), ('דוד'), ('שלמה'), ('אליהו'), ('ישעיהו'), ('ירמיהו'),
  ('יחזקאל'), ('דניאל'), ('הושע'), ('יואל'), ('עמוס'), ('עובדיה'), ('יונה'), ('מיכה'), ('נחום'), ('חבקוק'),
  ('צפניה'), ('חגי'), ('זכריה'), ('מלאכי'), ('שרה'), ('רבקה'), ('רחל'), ('לאה'), ('מרים'), ('דבורה'),
  ('רות'), ('חנה'), ('אביגיל'), ('אסתר'), ('עדינה'), ('שושנה'), ('יעל'), ('תמר'), ('נעמי'), ('חוה'),
  ('Benjamin'), ('Oliver'), ('Elijah'), ('William'), ('James'), ('Henry'), ('Alexander'), ('Michael'), ('Daniel'), ('Jacob'),
  ('Logan'), ('Jackson'), ('Levi'), ('Sebastian'), ('Mateo'), ('Jack'), ('Owen'), ('Theodore'), ('Aiden'), ('Samuel'),
  ('Joseph'), ('John'), ('David'), ('Wyatt'), ('Matthew'), ('Luke'), ('Asher'), ('Carter'), ('Julian'), ('Grayson'),
  ('Leo'), ('Jayden'), ('Gabriel'), ('Isaac'), ('Lincoln'), ('Anthony'), ('Hudson'), ('Dylan'), ('Ezra'), ('Thomas'),
  ('Emma'), ('Olivia'), ('Ava'), ('Isabella'), ('Sophia'), ('Charlotte'), ('Mia'), ('Amelia'), ('Harper'), ('Evelyn'),
  ('Abigail'), ('Emily'), ('Elizabeth'), ('Mila'), ('Ella'), ('Avery'), ('Sofia'), ('Camila'), ('Aria'), ('Scarlett'),
  ('Victoria'), ('Madison'), ('Luna'), ('Grace'), ('Chloe'), ('Penelope'), ('Layla'), ('Riley'), ('Zoey'), ('Nora'),
  ('Lily'), ('Eleanor'), ('Hannah'), ('Lillian'), ('Addison'), ('Aubrey'), ('Ellie'), ('Stella'), ('Natalie'), ('Zoe'),
  ('محمد'), ('أحمد'), ('محمود'), ('علي'), ('حسن'), ('حسين'), ('عمر'), ('خالد'), ('يوسف'), ('إبراهيم'),
  ('عبدالله'), ('عبدالرحمن'), ('سعد'), ('فهد'), ('تركي'), ('بندر'), ('راشد'), ('ناصر'), ('سلطان'), ('مشعل'),
  ('فاطمة'), ('عائشة'), ('خديجة'), ('زينب'), ('مريم'), ('سارة'), ('نور'), ('هدى'), ('أمل'), ('رانيا'),
  ('ليلى'), ('سمية'), ('جميلة'), ('كريمة'), ('حليمة'), ('صفية'), ('أسماء'), ('ريم'), ('منى'), ('وفاء'),
  ('Alex'), ('Sam'), ('Jordan'), ('Taylor'), ('Casey'), ('Riley'), ('Avery'), ('Quinn'), ('Sage'), ('River'),
  ('Phoenix'), ('Rowan'), ('Skyler'), ('Cameron'), ('Hayden'), ('Peyton'), ('Emery'), ('Finley'), ('Kai'), ('Remy'),
  ('Blake'), ('Reese'), ('Charlie'), ('Dakota'), ('Parker'), ('Emerson'), ('Sawyer'), ('Harley'), ('Kendall'), ('London'),
  ('זוהר'), ('נועם'), ('רוני'), ('שחר'), ('ליאור'), ('תומר'), ('עידו'), ('רועי'), ('גל'), ('עומר'),
  ('אורי'), ('עדי'), ('ניר'), ('אלון'), ('דור'), ('אסף'), ('איתי'), ('מתן'), ('נדב'), ('שגיב'),
  ('שירה'), ('מיכל'), ('רינת'), ('טלי'), ('שירי'), ('רונית'), ('מיכל'), ('נטליה'), ('יעל'), ('שרון'),
  ('ענת'), ('לימור'), ('סיגל'), ('אורלי'), ('נירית'), ('רוית'), ('דנית'), ('עינת'), ('כרמית'), ('אביבה'),
  ('الكسندر'), ('نيكولاس'), ('ديمتري'), ('كونستانتين'), ('فلاديمير'), ('ايفان'), ('سيرجي'), ('اندريه'), ('ميخائيل'), ('يوري'),
  ('أنستازيا'), ('كاترينا'), ('أولغا'), ('تاتيانا'), ('إيرينا'), ('مارينا'), ('سفيتلانا'), ('ناتاليا'), ('إيلينا'), ('يوليا'),
  ('Marco.'), ('Giuseppe'), ('Francesco'), ('Antonio'), ('Alessandro'), ('Andrea'), ('Matteo'), ('Luca'), ('Giovanni'), ('Davide'),
  ('Giulia'), ('Francesca'), ('Chiara'), ('Sara'), ('Valentina'), ('Alessandra'), ('Martina'), ('Federica'), ('Laura'), ('Silvia'),
  ('Pedro'), ('José'), ('Manuel'), ('Francisco'), ('David'), ('Juan'), ('Antonio'), ('Jesús'), ('Alejandro'), ('Miguel'),
  ('María'), ('Carmen'), ('Josefa'), ('Isabel'), ('Ana'), ('Dolores'), ('Pilar'), ('Teresa'), ('Rosa'), ('Francisca'),
  ('Jean'), ('Michel'), ('Pierre'), ('Philippe'), ('Alain'), ('Nicolas'), ('Christophe'), ('Laurent'), ('Thierry'), ('Stéphane'),
  ('Marie'), ('Monique'), ('Françoise'), ('Catherine'), ('Nathalie'), ('Isabelle'), ('Sylvie'), ('Christine'), ('Valérie'), ('Sandrine'),
  ('André'), ('João'), ('Paulo'), ('Carlos'), ('José'), ('António'), ('Manuel'), ('Fernando'), ('Luis'), ('Miguel'),
  ('Maria'), ('Ana'), ('Manuela'), ('Helena'), ('Isabel'), ('Teresa'), ('Cristina'), ('Fernanda'), ('Conceição'), ('Fátima'),
  ('Hans'), ('Peter'), ('Wolfgang'), ('Klaus'), ('Jürgen'), ('Dieter'), ('Helmut'), ('Horst'), ('Gerhard'), ('Uwe'),
  ('Ursula'), ('Ingrid'), ('Christa'), ('Gisela'), ('Monika'), ('Barbara'), ('Elisabeth'), ('Helga'), ('Renate'), ('Brigitte'),
  ('Lars'), ('Nils'), ('Erik'), ('Anders'), ('Magnus'), ('Johan'), ('Mikael'), ('Peter'), ('Daniel'), ('Andreas'),
  ('Anna'), ('Eva'), ('Maria'), ('Karin'), ('Kristina'), ('Margareta'), ('Elisabeth'), ('Birgitta'), ('Lena'), ('Marie'),
  ('Владимир'), ('Сергей'), ('Александр'), ('Дмитрий'), ('Андрей'), ('Алексей'), ('Михаил'), ('Евгений'), ('Николай'), ('Игорь'),
  ('Елена'), ('Ольга'), ('Татьяна'), ('Наталья'), ('Ирина'), ('Светлана'), ('Марина'), ('Людмила'), ('Анна'), ('Екатерина'),
  ('山田'), ('佐藤'), ('田中'), ('伊藤'), ('渡辺'), ('中村'), ('小林'), ('加藤'), ('吉田'), ('山本'),
  ('さくら'), ('あき'), ('みき'), ('ゆき'), ('けい'), ('まり'), ('あい'), ('り'), ('な'), ('ゆい'),
  ('이민수'), ('김철수'), ('박영희'), ('최영수'), ('정민호'), ('강혜진'), ('조성민'), ('윤서연'), ('임지훈'), ('한미영'),
  ('PlayeMaster'), ('GameGuru'), ('TileKing'), ('RummyPro'), ('CardShark'), ('WinnerX'), ('LuckyPlayer'), ('TopGamer'),
  ('SkillMaster'), ('ChampionZ'), ('VictoryOne'), ('ProPlayer'), ('EliteGamer'), ('MasterX'), ('WizardY'), ('AcePlayer'),
  ('StarGamer'), ('LegendZ'), ('HeroPlayer'), ('SuperStar'), ('MegaWin'), ('UltraPlayer'), ('PowerUser'), ('GrandMaster'),
  ('TileMaster'), ('RummyKing'), ('CardPro'), ('WinExpert'), ('GameChamp'), ('SkillWin'), ('ProWinner'), ('TopSkill'),
  ('MasterPlay'), ('ChampWin'), ('VictoryPro'), ('EliteWin'), ('StarPlay'), ('LegendWin'), ('HeroGame'), ('SuperPro'),
  ('MegaPro'), ('UltraWin'), ('PowerPro'), ('GrandWin'), ('TileWin'), ('RummyWin'), ('CardWin'), ('ProSkill'),
  ('נינג׳ה'), ('סמוראי'), ('גיבור'), ('לוחם'), ('אביר'), ('מלך'), ('נסיך'), ('קוסם'), ('כשף'), ('דרקון'),
  ('נמר'), ('אריה'), ('נשר'), ('זאב'), ('דוב'), ('פנתר'), ('בז'), ('עקרב'), ('קוברה'), ('פלקון'),
  ('אש'), ('מים'), ('רוח'), ('אדמה'), ('ברק'), ('קרח'), ('אור'), ('חושך'), ('כוכב'), ('ירח'),
  ('שמש'), ('ענן'), ('גשם'), ('שלג'), ('רעם'), ('ברק'), ('צונאמי'), ('סופה'), ('הוריקן'), ('סייקלון'),
  ('ديناميت'), ('صاروخ'), ('برق'), ('رعد'), ('عاصفة'), ('إعصار'), ('تسونامي'), ('زلزال'), ('بركان'), ('نار'),
  ('ماء'), ('هواء'), ('تراب'), ('ثلج'), ('جليد'), ('ضوء'), ('ظلام'), ('نجم'), ('قمر'), ('شمس'),
  ('سحاب'), ('مطر'), ('عاصفة'), ('رياح'), ('صحراء'), ('بحر'), ('جبل'), ('وادي'), ('نهر'), ('بحيرة'),
  ('غابة'), ('حقل'), ('مرج'), ('حديقة'), ('زهرة'), ('شجرة'), ('ورقة'), ('فرع'), ('جذر'), ('ثمرة'),
  ('בלאדמאסטר'), ('שאדוכלל'), ('פלאמסטרייק'), ('איסבלייד'), ('סטורמברינג'), ('איירווולקר'), ('רוקברייקר'), ('מיסטורד'),
  ('לייטספיד'), ('דארקנייט'), ('קולדהארט'), ('פיירבול'), ('איסשארד'), ('ווינדבלייד'), ('ארתקוויק'), ('לייטנינג'),
  ('ThunderStrike'), ('IceCold'), ('FireBall'), ('WindBlade'), ('EarthShake'), ('LightSpeed'), ('DarkNight'), ('StormBring'),
  ('FlameStrike'), ('IceBlade'), ('AirWalker'), ('RockBreaker'), ('MistLord'), ('ShadowKill'), ('BloodMaster'), ('SoulTaker'),
  ('DeathBlow'), ('LifeStealer'), ('MindBender'), ('TimeWarp'), ('SpaceRift'), ('VoidWalker'), ('ChaosLord'), ('OrderKeep'),
  ('מקסימום'), ('מינימום'), ('אופטימום'), ('פרימיום'), ('סופרים'), ('מגה'), ('גיגה'), ('טרה'), ('אולטרה'), ('סופר'),
  ('היפר'), ('טורבו'), ('ניטרו'), ('אטומי'), ('קוונטום'), ('דיגיטל'), ('סייבר'), ('טכנו'), ('נאו'), ('רטרו'),
  ('Maximum'), ('Minimum'), ('Optimum'), ('Premium'), ('Supreme'), ('Mega'), ('Giga'), ('Tera'), ('Ultra'), ('Super'),
  ('Hyper'), ('Turbo'), ('Nitro'), ('Atomic'), ('Quantum'), ('Digital'), ('Cyber'), ('Techno'), ('Neo'), ('Retro'),
  ('ألفا'), ('بيتا'), ('جاما'), ('دلتا'), ('أوميجا'), ('سيجما'), ('فاي'), ('بساي'), ('كاي'), ('لامدا'),
  ('Alpha'), ('Beta'), ('Gamma'), ('Delta'), ('Omega'), ('Sigma'), ('Phi'), ('Psi'), ('Chi'), ('Lambda'),
  ('Theta'), ('Epsilon'), ('Zeta'), ('Eta'), ('Iota'), ('Kappa'), ('Mu'), ('Nu'), ('Xi'), ('Omicron'),
  ('Pi'), ('Rho'), ('Tau'), ('Upsilon'), ('Xi'), ('Zeta'), ('Gamma'), ('Delta'), ('Epsilon'), ('Theta'),
  ('Speed'), ('Power'), ('Force'), ('Energy'), ('Magic'), ('Spirit'), ('Soul'), ('Heart'), ('Mind'), ('Will'),
  ('Dream'), ('Vision'), ('Hope'), ('Faith'), ('Love'), ('Peace'), ('Joy'), ('Light'), ('Dark'), ('Shadow'),
  ('Flame'), ('Frost'), ('Storm'), ('Wind'), ('Earth'), ('Water'), ('Fire'), ('Ice'), ('Thunder'), ('Lightning'),
  ('Blaze'), ('Freeze'), ('Shock'), ('Crush'), ('Strike'), ('Slash'), ('Pierce'), ('Block'), ('Guard'), ('Shield'),
  ('Sword'), ('Blade'), ('Arrow'), ('Spear'), ('Hammer'), ('Axe'), ('Bow'), ('Staff'), ('Wand'), ('Rod'),
  ('Crown'), ('Ring'), ('Gem'), ('Stone'), ('Crystal'), ('Diamond'), ('Ruby'), ('Emerald'), ('Sapphire'), ('Pearl');